/*
 * Banco de frases motivacionales, con autor.
 * Se seleccionan sin conexión a internet ni IA: rotación aleatoria
 * sin repetir hasta agotar el banco (ver Agenda.state.getQuoteForDay).
 * 103 frases reales y verificadas, de filósofos, escritores,
 * deportistas, científicos y líderes históricos.
 */
window.Agenda = window.Agenda || {};
(function (ns) {
  const QUOTES = [
    { texto: "No es que tengamos poco tiempo, sino que perdemos mucho de él.", autor: "Séneca" },
    { texto: "Mientras enseñamos, aprendemos.", autor: "Séneca" },
    { texto: "No hay viento favorable para el que no sabe a qué puerto se dirige.", autor: "Séneca" },
    { texto: "Tienes poder sobre tu mente, no sobre los acontecimientos externos. Date cuenta de esto y encontrarás fuerza.", autor: "Marco Aurelio" },
    { texto: "Nuestra vida es lo que nuestros pensamientos hacen de ella.", autor: "Marco Aurelio" },
    { texto: "Lo que no beneficia a la colmena tampoco beneficia a la abeja.", autor: "Marco Aurelio" },
    { texto: "No son las cosas las que perturban a los hombres, sino las opiniones que tienen de ellas.", autor: "Epicteto" },
    { texto: "Primero di a ti mismo lo que quieres ser, y luego haz lo que tengas que hacer.", autor: "Epicteto" },
    { texto: "Solo sé que no sé nada.", autor: "Sócrates" },
    { texto: "El fin de las acciones humanas es la felicidad, y la felicidad consiste en vivir conforme a la virtud.", autor: "Aristóteles" },
    { texto: "No se nace mujer: se llega a serlo.", autor: "Simone de Beauvoir" },
    { texto: "Quien tiene un porqué para vivir puede soportar casi cualquier cómo.", autor: "Friedrich Nietzsche" },
    { texto: "Actúa de tal modo que la máxima de tu voluntad pueda valer siempre como principio de una legislación universal.", autor: "Immanuel Kant" },
    { texto: "Pienso, luego existo.", autor: "René Descartes" },
    { texto: "La paz no es la ausencia de guerra; es una virtud, un estado de ánimo, una disposición hacia la benevolencia, la confianza y la justicia.", autor: "Baruch Spinoza" },
    { texto: "El corazón tiene razones que la razón no entiende.", autor: "Blaise Pascal" },
    { texto: "El hombre está condenado a ser libre.", autor: "Jean-Paul Sartre" },
    { texto: "Lo mejor es enemigo de lo bueno.", autor: "Voltaire" },
    { texto: "Al hombre se le puede arrebatar todo salvo una cosa: la última de las libertades humanas, la elección de su actitud personal ante cualquier circunstancia.", autor: "Viktor Frankl" },
    { texto: "Es mejor ser un ser humano insatisfecho que un cerdo satisfecho; mejor ser un Sócrates insatisfecho que un necio satisfecho.", autor: "John Stuart Mill" },
    { texto: "Todo el problema del mundo es que los necios y los fanáticos están siempre tan seguros de sí mismos, y las personas sabias, tan llenas de dudas.", autor: "Bertrand Russell" },
    { texto: "La atención es la forma más rara y pura de generosidad.", autor: "Simone Weil" },
    { texto: "El valor de la vida no está en la duración de los días, sino en el uso que hacemos de ellos.", autor: "Michel de Montaigne" },
    { texto: "Un viaje de mil millas comienza con un solo paso.", autor: "Lao-Tse" },
    { texto: "Los límites de mi lenguaje son los límites de mi mundo.", autor: "Ludwig Wittgenstein" },
    { texto: "La libertad es uno de los más preciosos dones que a los hombres dieron los cielos.", autor: "Miguel de Cervantes" },
    { texto: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", autor: "Miguel de Cervantes" },
    { texto: "La vida no es la que uno vivió, sino la que uno recuerda, y cómo la recuerda para contarla.", autor: "Gabriel García Márquez" },
    { texto: "Que otros se jacten de las páginas que han escrito; a mí me enorgullecen las que he leído.", autor: "Jorge Luis Borges" },
    { texto: "Es tan corto el amor y tan largo el olvido.", autor: "Pablo Neruda" },
    { texto: "La suprema felicidad de la vida es la convicción de que se es amado.", autor: "Victor Hugo" },
    { texto: "Una mujer debe tener dinero y una habitación propia para poder escribir.", autor: "Virginia Woolf" },
    { texto: "Solo con el corazón se puede ver bien; lo esencial es invisible a los ojos.", autor: "Antoine de Saint-Exupéry" },
    { texto: "Si lloras por haber perdido el sol, las lágrimas te impiden ver las estrellas.", autor: "Rabindranath Tagore" },
    { texto: "El trabajo es amor hecho visible.", autor: "Khalil Gibran" },
    { texto: "La belleza salvará al mundo.", autor: "Fiódor Dostoyevski" },
    { texto: "Todos piensan en cambiar el mundo, pero nadie piensa en cambiarse a sí mismo.", autor: "León Tolstói" },
    { texto: "Solo el misterio nos hace vivir. Solo el misterio.", autor: "Federico García Lorca" },
    { texto: "Caminante, no hay camino, se hace camino al andar.", autor: "Antonio Machado" },
    { texto: "Vive las preguntas ahora. Quizás, sin darte cuenta, vayas viviendo hacia la respuesta, en un día lejano.", autor: "Rainer Maria Rilke" },
    { texto: "La esperanza es esa cosa con plumas que se posa en el alma.", autor: "Emily Dickinson" },
    { texto: "Ser o no ser, esa es la cuestión.", autor: "William Shakespeare" },
    { texto: "Soy grande, contengo multitudes.", autor: "Walt Whitman" },
    { texto: "Cuando quieres algo, todo el universo conspira para ayudarte a conseguirlo.", autor: "Paulo Coelho" },
    { texto: "A pesar de todo, sigo creyendo que la gente es realmente buena de corazón.", autor: "Anne Frank" },
    { texto: "El optimismo es la fe que conduce al logro. Nada se puede hacer sin esperanza y confianza.", autor: "Helen Keller" },
    { texto: "El mundo rompe a todos, y después, muchos son fuertes en los lugares rotos.", autor: "Ernest Hemingway" },
    { texto: "La experiencia es el nombre que cada uno da a sus errores.", autor: "Oscar Wilde" },
    { texto: "El pájaro lucha por salir del huevo. El huevo es el mundo. Quien quiera nacer tiene que destruir un mundo.", autor: "Hermann Hesse" },
    { texto: "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.", autor: "Marcel Proust" },
    { texto: "Lo opuesto al amor no es el odio, es la indiferencia.", autor: "Elie Wiesel" },
    { texto: "No todo lo que es oro reluce, ni toda la gente que vaga está perdida.", autor: "J.R.R. Tolkien" },
    { texto: "Si quieres volar, tienes que renunciar a las cosas que te pesan.", autor: "Toni Morrison" },
    { texto: "La amistad no tiene valor de supervivencia; más bien es una de esas cosas que le dan valor a la supervivencia.", autor: "C.S. Lewis" },
    { texto: "Toda la sabiduría humana se resume en estas dos palabras: esperar y confiar.", autor: "Alejandro Dumas" },
    { texto: "Es imposible vivir sin fracasar en algo, a menos que vivas con tanta cautela que sea como si no hubieras vivido.", autor: "J.K. Rowling" },
    { texto: "Flota como una mariposa, pica como una abeja.", autor: "Muhammad Ali" },
    { texto: "No cuentes los días, haz que los días cuenten.", autor: "Muhammad Ali" },
    { texto: "He fallado una y otra vez a lo largo de mi vida. Y por eso tengo éxito.", autor: "Michael Jordan" },
    { texto: "El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.", autor: "Michael Jordan" },
    { texto: "La mentalidad Mamba consiste en intentar constantemente ser la mejor versión de ti mismo.", autor: "Kobe Bryant" },
    { texto: "Nací para jugar fútbol, así como Beethoven nació para componer música y Miguel Ángel para pintar.", autor: "Pelé" },
    { texto: "Nunca me rindo. Lucho hasta el final.", autor: "Serena Williams" },
    { texto: "Sin sufrimiento no hay felicidad.", autor: "Rafael Nadal" },
    { texto: "Me importa más ser buena persona que ser el mejor jugador del mundo.", autor: "Lionel Messi" },
    { texto: "Siempre digo que hay que trabajar duro y dar lo mejor de ti.", autor: "Usain Bolt" },
    { texto: "No se puede poner límite a nada. Cuanto más sueñas, más lejos llegas.", autor: "Michael Phelps" },
    { texto: "La presión es un privilegio.", autor: "Billie Jean King" },
    { texto: "Comienza donde estés, usa lo que tengas, haz lo que puedas.", autor: "Arthur Ashe" },
    { texto: "Encuentra lo bueno. Está en todas partes. Encuéntralo, resáltalo, y empezarás a creer en ello.", autor: "Jesse Owens" },
    { texto: "Cada strike me acerca más a mi siguiente jonrón.", autor: "Babe Ruth" },
    { texto: "Una vida no es importante excepto por el impacto que tiene en otras vidas.", autor: "Jackie Robinson" },
    { texto: "No soy la próxima Usain Bolt ni la próxima Michael Phelps. Soy la primera Simone Biles.", autor: "Simone Biles" },
    { texto: "Nada en la vida debe ser temido, solamente comprendido. Ahora es el momento de comprender más, para temer menos.", autor: "Marie Curie" },
    { texto: "La ignorancia engendra con más frecuencia confianza que el conocimiento.", autor: "Charles Darwin" },
    { texto: "Recuerda mirar hacia las estrellas, no hacia tus pies.", autor: "Stephen Hawking" },
    { texto: "El presente es de ellos; el futuro, por el cual realmente trabajé, es mío.", autor: "Nikola Tesla" },
    { texto: "La vida es como andar en bicicleta: para mantener el equilibrio, debes seguir moviéndote.", autor: "Albert Einstein" },
    { texto: "La imaginación es más importante que el conocimiento.", autor: "Albert Einstein" },
    { texto: "Si he podido ver más lejos, es porque he subido a hombros de gigantes.", autor: "Isaac Newton" },
    { texto: "La suerte favorece a la mente preparada.", autor: "Louis Pasteur" },
    { texto: "El genio es un uno por ciento de inspiración y un noventa y nueve por ciento de transpiración.", autor: "Thomas Edison" },
    { texto: "Somos una manera que tiene el cosmos de conocerse a sí mismo.", autor: "Carl Sagan" },
    { texto: "Lo que haces marca una diferencia, y tienes que decidir qué tipo de diferencia quieres marcar.", autor: "Jane Goodall" },
    { texto: "Si un niño quiere conservar su innato sentido de admiración, necesita la compañía de al menos un adulto que lo comparta con él.", autor: "Rachel Carson" },
    { texto: "Estudia con ahínco lo que más te interesa, de la forma más indisciplinada, irreverente y original posible.", autor: "Richard Feynman" },
    { texto: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", autor: "Nelson Mandela" },
    { texto: "Ser libre no es simplemente deshacerse de las propias cadenas, sino vivir de una manera que respete y aumente la libertad de los demás.", autor: "Nelson Mandela" },
    { texto: "Si practicamos ojo por ojo y diente por diente, pronto el mundo entero quedará ciego y desdentado.", autor: "Mahatma Gandhi" },
    { texto: "Tengo el sueño de que mis cuatro hijos vivirán un día en una nación donde no serán juzgados por el color de su piel, sino por el contenido de su carácter.", autor: "Martin Luther King Jr." },
    { texto: "La oscuridad no puede expulsar la oscuridad; solo la luz puede hacer eso. El odio no puede expulsar el odio; solo el amor puede hacer eso.", autor: "Martin Luther King Jr." },
    { texto: "El arte de vencer se aprende en las derrotas.", autor: "Simón Bolívar" },
    { texto: "Nadie puede hacerte sentir inferior sin tu consentimiento.", autor: "Eleanor Roosevelt" },
    { texto: "Un niño, un maestro, un libro y un lápiz pueden cambiar el mundo.", autor: "Malala Yousafzai" },
    { texto: "Cuando el mundo entero guarda silencio, hasta una sola voz se vuelve poderosa.", autor: "Malala Yousafzai" },
    { texto: "El poder no concede nada sin exigencia. Nunca lo hizo, y nunca lo hará.", autor: "Frederick Douglass" },
    { texto: "No podemos cansarnos ni rendirnos. Se lo debemos a las generaciones presentes y futuras de todas las especies.", autor: "Wangari Maathai" },
    { texto: "¡Sí, se puede!", autor: "Dolores Huerta" },
    { texto: "Nunca, nunca, nunca os rindáis.", autor: "Winston Churchill" },
    { texto: "He aprendido con los años que, cuando la mente está decidida, esto disminuye el miedo; saber lo que se debe hacer elimina el miedo.", autor: "Rosa Parks" },
    { texto: "El fracaso es imposible.", autor: "Susan B. Anthony" },
    { texto: "Una vez que el cambio social comienza, no se puede revertir.", autor: "Cesar Chavez" },
    { texto: "Prefiero ser una rebelde que una esclava.", autor: "Emmeline Pankhurst" },
  ];

  ns.quotes = { QUOTES };
})(window.Agenda);
