/*
 * Banco de frases motivacionales.
 * Se seleccionan sin conexión a internet ni IA: rotación aleatoria
 * sin repetir hasta agotar el banco (ver Agenda.state.getQuoteForDay).
 */
window.Agenda = window.Agenda || {};
(function (ns) {
  const QUOTES = [
    "El orden de hoy es la calma de mañana.",
    "Pequeños pasos constantes vencen a los grandes impulsos ocasionales.",
    "Disciplina es elegir entre lo que quieres ahora y lo que quieres más.",
    "No necesitas ver todo el camino, solo el siguiente paso.",
    "Lo que se mide y se anota, se mejora.",
    "Un día bien planeado vale más que una semana improvisada.",
    "La claridad llega haciendo, no solo pensando.",
    "Termina lo que empezaste antes de empezar algo nuevo.",
    "El hábito construye lo que la motivación no puede sostener.",
    "Hoy es una oportunidad nueva, no una repetición de ayer.",
    "Avanzar poco es mejor que no avanzar nada.",
    "La constancia vence al talento cuando el talento no es constante.",
    "Primero lo importante, después lo urgente.",
    "Cada hora bien usada es una inversión en ti mismo.",
    "El descanso también es parte del trabajo bien hecho.",
    "No se trata de tener tiempo, se trata de decidir usarlo bien.",
    "Una meta sin fecha es solo un deseo.",
    "El progreso silencioso también cuenta.",
    "Se empieza por orden, se sigue por costumbre.",
    "Lo simple, bien ejecutado, gana a lo complejo a medias.",
    "El mejor momento para empezar fue ayer; el segundo mejor es ahora.",
    "Cuida los procesos y los resultados llegarán.",
    "La energía se administra, no solo se gasta.",
    "Un plan imperfecto en marcha vale más que uno perfecto sin empezar.",
    "La calidad de tus días define la calidad de tu vida.",
    "No compitas contra otros, compite contra quien fuiste ayer.",
    "El enfoque es decidir qué NO hacer hoy.",
    "Cada tarea terminada libera espacio mental para la siguiente.",
    "La paciencia también es una forma de trabajar.",
    "Ordenar el día es ordenar la mente.",
    "Ser constante en lo pequeño te prepara para lo grande.",
    "El descuido de un día se nota en la suma de una semana.",
    "Hazlo bien una vez, no lo repitas cinco.",
    "Lo que no se planea, rara vez se cumple.",
    "El esfuerzo de hoy es el resultado de mañana.",
    "Cuando dudes, vuelve a lo básico: la rutina sostiene.",
    "El tiempo que cuidas hoy, lo agradeces después.",
    "Cada hábito cumplido es un voto por quien quieres ser.",
    "No busques el momento perfecto, crea el momento adecuado.",
    "La disciplina silenciosa vale más que la motivación ruidosa.",
    "Prioriza sin culpa: no todo puede ser lo primero.",
    "El descanso planeado rinde más que el descanso improvisado.",
    "Revisa tu semana para no repetir los mismos tropiezos.",
    "Un buen inicio de día multiplica el resto de las horas.",
    "La consistencia es el interés compuesto del esfuerzo.",
    "Menos pendientes sueltos, más foco real.",
    "Lo que ordenas por la mañana, lo agradeces por la noche.",
    "El trabajo bien distribuido pesa menos.",
    "Cumplir lo pequeño con seriedad entrena para lo grande.",
    "El progreso no siempre se ve, pero se acumula.",
    "Cada agenda cumplida es una promesa que te hiciste y sostuviste.",
    "No se trata de hacer más, sino de hacer lo correcto.",
    "La rutina bien hecha da libertad, no la quita.",
    "Empieza por lo que más resistencia te da: ahí está el avance real.",
    "Hoy decide, mañana agradece.",
    "El equilibrio se construye día a día, no de una sola vez.",
    "Ser ordenado con el tiempo es una forma de respeto propio.",
    "Lo que se anota se recuerda; lo que se recuerda, se cumple.",
    "La mejora es un proceso de ajustes pequeños y constantes.",
    "Cierra bien el día para abrir bien el siguiente.",
    "El esfuerzo sin dirección se dispersa; con agenda, se acumula.",
    "Cada semana revisada es una semana que rinde más.",
    "Ir despacio pero sin pausa también es avanzar.",
    "El compromiso con uno mismo empieza en los detalles del día.",
    "No hay agenda perfecta, hay agenda que se usa.",
  ];

  ns.quotes = { QUOTES };
})(window.Agenda);
