/*
 * Banco de "Palabra del día", con significado en español e inglés.
 * Mismo mecanismo que Agenda.quotes: rotación aleatoria sin repetir
 * hasta agotar el banco (ver Agenda.state.getWordForDay). 103 palabras,
 * una por cada día que queda del año.
 */
window.Agenda = window.Agenda || {};
(function (ns) {
  const WORDS = [
    { palabra: "Efímero", significadoEs: "Que dura poco tiempo, pasajero.", significadoEn: "Ephemeral; lasting for a very short time." },
    { palabra: "Quimera", significadoEs: "Ilusión o proyecto que se considera imposible de realizar.", significadoEn: "A chimera; a hope or dream that seems impossible to achieve." },
    { palabra: "Melancolía", significadoEs: "Tristeza vaga, profunda y permanente.", significadoEn: "Melancholy; a deep, pensive, long-lasting sadness." },
    { palabra: "Nostalgia", significadoEs: "Pena que causa el recuerdo de un bien perdido.", significadoEn: "Nostalgia; a sentimental longing for the past." },
    { palabra: "Añoranza", significadoEs: "Sentimiento de tristeza por la ausencia de algo o alguien querido.", significadoEn: "Longing; a wistful yearning for someone or something absent." },
    { palabra: "Desasosiego", significadoEs: "Falta de sosiego, intranquilidad.", significadoEn: "Restlessness; a state of unease or disquiet." },
    { palabra: "Ensimismamiento", significadoEs: "Estado de quien está absorto en sus propios pensamientos.", significadoEn: "Self-absorption; being deeply lost in one's own thoughts." },
    { palabra: "Crepúsculo", significadoEs: "Claridad que hay al amanecer o al anochecer.", significadoEn: "Twilight; the soft light after sunset or before sunrise." },
    { palabra: "Alborada", significadoEs: "Tiempo que comprende el amanecer, o música que se toca al alba.", significadoEn: "Dawn; daybreak, or music traditionally played at first light." },
    { palabra: "Cenit", significadoEs: "Punto más alto o momento de mayor esplendor de algo.", significadoEn: "Zenith; the highest point or peak of something." },
    { palabra: "Ocaso", significadoEs: "Puesta del sol; también, decadencia o final de algo.", significadoEn: "Sunset; also, the decline or end of something." },
    { palabra: "Estío", significadoEs: "Verano.", significadoEn: "Summer (a literary term for the season)." },
    { palabra: "Gélido", significadoEs: "Muy frío, helado.", significadoEn: "Gelid; intensely cold." },
    { palabra: "Tórrido", significadoEs: "Muy caluroso, abrasador.", significadoEn: "Torrid; extremely hot." },
    { palabra: "Apacible", significadoEs: "Tranquilo, sosegado y agradable.", significadoEn: "Peaceful; calm, gentle and pleasant." },
    { palabra: "Plácido", significadoEs: "Tranquilo, sereno, sin sobresaltos.", significadoEn: "Placid; calm and untroubled." },
    { palabra: "Sereno", significadoEs: "Tranquilo, apacible, sin alteración.", significadoEn: "Serene; calm and composed." },
    { palabra: "Borrascoso", significadoEs: "Tempestuoso, agitado.", significadoEn: "Stormy; turbulent or tempestuous." },
    { palabra: "Ubicuo", significadoEs: "Que está presente al mismo tiempo en todas partes.", significadoEn: "Ubiquitous; seeming to be present everywhere at once." },
    { palabra: "Efervescente", significadoEs: "Que produce burbujas; también, muy animado y entusiasta.", significadoEn: "Effervescent; bubbly, or vivaciously enthusiastic." },
    { palabra: "Vehemente", significadoEs: "Que actúa o se expresa con mucha pasión e intensidad.", significadoEn: "Vehement; showing strong, passionate feeling." },
    { palabra: "Lacónico", significadoEs: "Que se expresa con pocas palabras.", significadoEn: "Laconic; using very few words to express something." },
    { palabra: "Verborrea", significadoEs: "Uso excesivo e innecesario de palabras al hablar o escribir.", significadoEn: "Verbosity; the excessive and unnecessary use of words." },
    { palabra: "Meticuloso", significadoEs: "Que cuida mucho los detalles al hacer algo.", significadoEn: "Meticulous; showing great attention to detail." },
    { palabra: "Diáfano", significadoEs: "Transparente, que deja pasar la luz con claridad.", significadoEn: "Diaphanous; translucent or clear." },
    { palabra: "Opulento", significadoEs: "Que tiene abundancia de riquezas o lujo.", significadoEn: "Opulent; lavishly rich or luxurious." },
    { palabra: "Austero", significadoEs: "Sobrio, sencillo, sin lujos ni adornos.", significadoEn: "Austere; simple and severe, without luxury." },
    { palabra: "Exiguo", significadoEs: "Insuficiente, escaso.", significadoEn: "Meager; scanty or insufficient." },
    { palabra: "Ingente", significadoEs: "Muy grande, enorme.", significadoEn: "Huge; immense in size." },
    { palabra: "Mordaz", significadoEs: "Que critica con agudeza, ironía o sarcasmo.", significadoEn: "Mordant; sharply critical, ironic or sarcastic." },
    { palabra: "Sagaz", significadoEs: "Que tiene agudeza e inteligencia para comprender y prever las cosas.", significadoEn: "Sagacious; having keen judgment and foresight." },
    { palabra: "Perspicaz", significadoEs: "Que tiene capacidad para percibir o entender las cosas con claridad.", significadoEn: "Perceptive; having keen insight or understanding." },
    { palabra: "Incólume", significadoEs: "Que no ha sufrido daño ni menoscabo.", significadoEn: "Unscathed; unharmed or undamaged." },
    { palabra: "Impávido", significadoEs: "Que no muestra miedo ante el peligro.", significadoEn: "Fearless; showing no fear in the face of danger." },
    { palabra: "Imperturbable", significadoEs: "Que no se altera ni se inmuta fácilmente.", significadoEn: "Imperturbable; calm and not easily upset or excited." },
    { palabra: "Inefable", significadoEs: "Que no se puede expresar con palabras.", significadoEn: "Ineffable; too great or intense to be expressed in words." },
    { palabra: "Indeleble", significadoEs: "Que no se puede borrar ni quitar.", significadoEn: "Indelible; making a mark that cannot be removed." },
    { palabra: "Inexorable", significadoEs: "Que no se puede evitar, detener o conmover.", significadoEn: "Inexorable; impossible to stop, avoid or persuade." },
    { palabra: "Insondable", significadoEs: "Que no se puede conocer o comprender del todo.", significadoEn: "Unfathomable; impossible to fully understand or measure." },
    { palabra: "Arcano", significadoEs: "Secreto, misterioso, muy difícil de conocer.", significadoEn: "Arcane; mysterious, secret, and understood by very few." },
    { palabra: "Esotérico", significadoEs: "Oculto, reservado solo para quienes están iniciados en un tema.", significadoEn: "Esoteric; intended for or understood by only a small group." },
    { palabra: "Hermético", significadoEs: "Cerrado por completo; también, muy difícil de entender.", significadoEn: "Hermetic; completely sealed, or very difficult to understand." },
    { palabra: "Enigmático", significadoEs: "Que encierra un enigma o misterio.", significadoEn: "Enigmatic; mysterious and difficult to interpret." },
    { palabra: "Paradoja", significadoEs: "Idea que parece contradictoria o absurda pero puede ser cierta.", significadoEn: "Paradox; a statement that seems contradictory but may be true." },
    { palabra: "Dicotomía", significadoEs: "División de algo en dos partes opuestas o contradictorias.", significadoEn: "Dichotomy; a division into two sharply contrasting parts." },
    { palabra: "Anacronismo", significadoEs: "Error que consiste en situar algo fuera del tiempo que le corresponde.", significadoEn: "Anachronism; something placed in the wrong historical period." },
    { palabra: "Sinécdoque", significadoEs: "Figura retórica que nombra el todo por la parte, o viceversa.", significadoEn: "Synecdoche; a figure of speech naming a part for the whole, or vice versa." },
    { palabra: "Metonimia", significadoEs: "Figura retórica que sustituye un término por otro con el que guarda relación.", significadoEn: "Metonymy; a figure of speech substituting a term with a closely related one." },
    { palabra: "Oxímoron", significadoEs: "Combinación de dos palabras de significado opuesto.", significadoEn: "Oxymoron; a combination of two contradictory terms." },
    { palabra: "Hipérbole", significadoEs: "Exageración retórica de algo para darle más énfasis.", significadoEn: "Hyperbole; an exaggerated statement not meant to be taken literally." },
    { palabra: "Eufemismo", significadoEs: "Palabra o expresión suave que sustituye otra considerada dura o de mal gusto.", significadoEn: "Euphemism; a mild word substituted for one considered harsh or blunt." },
    { palabra: "Epifanía", significadoEs: "Manifestación repentina de la esencia o el significado de algo.", significadoEn: "Epiphany; a sudden and striking realization about something." },
    { palabra: "Catarsis", significadoEs: "Liberación emocional intensa y purificadora.", significadoEn: "Catharsis; an intense, purifying emotional release." },
    { palabra: "Letargo", significadoEs: "Estado de sopor o inactividad profunda.", significadoEn: "Lethargy; a state of deep sluggishness or inactivity." },
    { palabra: "Hastío", significadoEs: "Disgusto o fastidio que produce el exceso de algo.", significadoEn: "Weariness; boredom or disgust caused by an excess of something." },
    { palabra: "Tedio", significadoEs: "Aburrimiento, fastidio.", significadoEn: "Tedium; boredom or monotony." },
    { palabra: "Fruición", significadoEs: "Goce o deleite intenso al hacer algo.", significadoEn: "Relish; intense enjoyment or delight in doing something." },
    { palabra: "Embeleso", significadoEs: "Estado de fascinación o admiración profunda.", significadoEn: "Enchantment; a state of deep fascination or delight." },
    { palabra: "Algarabía", significadoEs: "Griterío o ruido confuso de varias personas hablando a la vez.", significadoEn: "Hubbub; a loud, confused noise of many voices at once." },
    { palabra: "Jolgorio", significadoEs: "Fiesta o diversión bulliciosa.", significadoEn: "Merrymaking; noisy revelry or festive fun." },
    { palabra: "Bullicio", significadoEs: "Ruido y agitación que produce mucha gente reunida.", significadoEn: "Bustle; the noisy commotion of a crowd." },
    { palabra: "Sosiego", significadoEs: "Calma, tranquilidad, quietud.", significadoEn: "Tranquility; calmness and peace of mind." },
    { palabra: "Desidia", significadoEs: "Falta de cuidado o de esfuerzo; negligencia.", significadoEn: "Negligence; carelessness or lack of effort." },
    { palabra: "Apatía", significadoEs: "Falta de emoción, motivación o interés.", significadoEn: "Apathy; a lack of interest, emotion or motivation." },
    { palabra: "Indolencia", significadoEs: "Pereza, falta de esfuerzo o de interés por actuar.", significadoEn: "Indolence; laziness or a lack of effort or interest." },
    { palabra: "Abulia", significadoEs: "Falta o debilidad de la voluntad para actuar.", significadoEn: "Abulia; a lack or weakness of willpower to act." },
    { palabra: "Morriña", significadoEs: "Nostalgia, especialmente la que se siente por la tierra natal.", significadoEn: "Homesickness; a longing for one's home or native land." },
    { palabra: "Congoja", significadoEs: "Angustia o aflicción del ánimo.", significadoEn: "Anguish; deep distress or sorrow." },
    { palabra: "Desazón", significadoEs: "Malestar, inquietud o disgusto interior.", significadoEn: "Unease; a feeling of inner discomfort or restlessness." },
    { palabra: "Zozobra", significadoEs: "Angustia o inquietud grande del ánimo.", significadoEn: "Anxiety; a state of great worry or unease." },
    { palabra: "Aprensión", significadoEs: "Recelo o temor de un daño futuro, a veces exagerado.", significadoEn: "Apprehension; anxiety or dread about something that may happen." },
    { palabra: "Recelo", significadoEs: "Desconfianza o sospecha hacia algo o alguien.", significadoEn: "Distrust; a feeling of suspicion or wariness." },
    { palabra: "Suspicacia", significadoEs: "Tendencia a sospechar o desconfiar de las intenciones ajenas.", significadoEn: "Suspicion; a tendency to distrust others' intentions." },
    { palabra: "Cavilación", significadoEs: "Reflexión insistente y detenida sobre algo.", significadoEn: "Rumination; deep, persistent thought about something." },
    { palabra: "Ensoñación", significadoEs: "Estado de quien imagina o fantasea despierto.", significadoEn: "Reverie; a state of dreamy, wakeful fantasy." },
    { palabra: "Espejismo", significadoEs: "Ilusión óptica; algo que parece real sin serlo.", significadoEn: "Mirage; an optical illusion, or something that seems real but is not." },
    { palabra: "Escarmiento", significadoEs: "Lección o advertencia que se aprende tras sufrir un daño.", significadoEn: "A hard-earned lesson learned from a painful experience." },
    { palabra: "Resiliencia", significadoEs: "Capacidad de adaptarse y recuperarse ante la adversidad.", significadoEn: "Resilience; the ability to recover from or adapt to difficulty." },
    { palabra: "Tenacidad", significadoEs: "Firmeza y constancia en la persecución de un propósito.", significadoEn: "Tenacity; persistence in pursuing a goal despite difficulty." },
    { palabra: "Entereza", significadoEs: "Fortaleza de ánimo para afrontar la adversidad.", significadoEn: "Fortitude; strength of mind in facing hardship." },
    { palabra: "Ecuanimidad", significadoEs: "Equilibrio y serenidad de ánimo, especialmente ante la dificultad.", significadoEn: "Equanimity; calmness and composure, especially under pressure." },
    { palabra: "Sensatez", significadoEs: "Cualidad de juzgar y actuar con buen criterio.", significadoEn: "Good sense; the quality of sound, prudent judgment." },
    { palabra: "Cordura", significadoEs: "Buen juicio, prudencia, sensatez.", significadoEn: "Prudence; good judgment and reasonableness." },
    { palabra: "Discernimiento", significadoEs: "Capacidad de distinguir y juzgar con acierto.", significadoEn: "Discernment; the ability to judge well and distinguish clearly." },
    { palabra: "Clarividencia", significadoEs: "Capacidad de comprender o prever las cosas con claridad.", significadoEn: "Clairvoyance; unusually clear insight or foresight." },
    { palabra: "Presciencia", significadoEs: "Conocimiento anticipado de algo que va a suceder.", significadoEn: "Prescience; foreknowledge of events before they happen." },
    { palabra: "Agudeza", significadoEs: "Ingenio y perspicacia para entender o expresar las cosas.", significadoEn: "Sharpness of wit; keen intelligence or insight." },
    { palabra: "Donaire", significadoEs: "Gracia y elegancia al hablar o moverse.", significadoEn: "Charm and grace in speech or movement." },
    { palabra: "Socarronería", significadoEs: "Ironía disimulada bajo una apariencia de seriedad o inocencia.", significadoEn: "Sly mockery; a mocking irony disguised as innocent seriousness." },
    { palabra: "Sorna", significadoEs: "Tono irónico y burlón con que se dice algo.", significadoEn: "Sarcasm; a mocking, ironic tone." },
    { palabra: "Vislumbrar", significadoEs: "Ver algo de forma confusa o a lo lejos.", significadoEn: "To glimpse; to see something faintly or from a distance." },
    { palabra: "Atisbar", significadoEs: "Mirar con cuidado y disimulo, o percibir algo apenas.", significadoEn: "To peer; to look cautiously, or to barely perceive something." },
    { palabra: "Escudriñar", significadoEs: "Examinar algo con mucha atención y detalle.", significadoEn: "To scrutinize; to examine something closely and carefully." },
    { palabra: "Ponderar", significadoEs: "Considerar algo con cuidado antes de decidir o juzgar.", significadoEn: "To ponder; to consider something carefully." },
    { palabra: "Dilucidar", significadoEs: "Aclarar un asunto difícil de entender.", significadoEn: "To elucidate; to make a difficult matter clear." },
    { palabra: "Desentrañar", significadoEs: "Descubrir el sentido oculto o profundo de algo.", significadoEn: "To unravel; to discover the hidden or deeper meaning of something." },
    { palabra: "Urdir", significadoEs: "Planear o preparar algo, generalmente de forma oculta.", significadoEn: "To scheme; to plot or plan something, often secretly." },
    { palabra: "Forjar", significadoEs: "Crear o dar forma a algo mediante esfuerzo constante.", significadoEn: "To forge; to shape or create something through sustained effort." },
    { palabra: "Subyacer", significadoEs: "Estar debajo de algo como base, causa o motivo oculto.", significadoEn: "To underlie; to be the hidden basis or cause of something." },
    { palabra: "Converger", significadoEs: "Dirigirse dos o más cosas hacia un mismo punto.", significadoEn: "To converge; to move toward a common point." },
    { palabra: "Propugnar", significadoEs: "Defender con esfuerzo una idea o causa.", significadoEn: "To advocate; to defend or promote an idea or cause." },
    { palabra: "Mitigar", significadoEs: "Suavizar o disminuir la intensidad de algo negativo.", significadoEn: "To mitigate; to make something harmful or severe less intense." },
    { palabra: "Sempiterno", significadoEs: "Que dura y durará siempre, sin fin.", significadoEn: "Everlasting; that which lasts and will always last, without end." },
  ];

  ns.wordOfTheDay = { WORDS };
})(window.Agenda);
